=begin
#AI Mastering API

#This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.

OpenAPI spec version: 1.0.0
Contact: info@bakuage.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Aimastering::AmazonSubscriptionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AmazonSubscriptionApi' do
  before do
    # run before each test
    @instance = Aimastering::AmazonSubscriptionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AmazonSubscriptionApi' do
    it 'should create an instance of AmazonSubscriptionApi' do
      expect(@instance).to be_instance_of(Aimastering::AmazonSubscriptionApi)
    end
  end

  # unit tests for list_amazon_subscriptions
  # Get all accessable amazon subscriptions.
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<AmazonSubscription>]
  describe 'list_amazon_subscriptions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
