=begin
#AI Mastering API

#This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.

OpenAPI spec version: 1.0.0
Contact: aimasteringcom@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Aimastering::ExternalSearchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExternalSearchApi' do
  before do
    # run before each test
    @instance = Aimastering::ExternalSearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalSearchApi' do
    it 'should create an instance of ExternalSearchApi' do
      expect(@instance).to be_instance_of(Aimastering::ExternalSearchApi)
    end
  end

  # unit tests for search_external
  # Search external music and get name, url, thumbnails, etc.
  # 
  # @param query Search query
  # @param country Country ex. US, JP, etc
  # @param [Hash] opts the optional parameters
  # @return [ExternalSearchResult]
  describe 'search_external test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
