=begin
#AI Mastering API

#This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.

OpenAPI spec version: 1.0.0
Contact: aimasteringcom@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Aimastering::VideoApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VideoApi' do
  before do
    # run before each test
    @instance = Aimastering::VideoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideoApi' do
    it 'should create an instance of VideoApi' do
      expect(@instance).to be_instance_of(Aimastering::VideoApi)
    end
  end

  # unit tests for download_video
  # Download an video data by id.
  # 
  # @param id Video id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for download_video_by_token
  # Download an video data by video_download_token.
  # 
  # @param download_token Video download token
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_video_by_token test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_video
  # Get an video by id.
  # 
  # @param id Video id
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'get_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_video_download_token
  # Get an video download token by id.
  # 
  # @param id Video id
  # @param [Hash] opts the optional parameters
  # @return [VideoDownloadToken]
  describe 'get_video_download_token test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_videos
  # Get all videos accessable.
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<Video>]
  describe 'list_videos test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
