=begin
#AI Mastering API

#This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.

OpenAPI spec version: 1.0.0
Contact: info@bakuage.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aimastering::Kpi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Kpi' do
  before do
    # run before each test
    @instance = Aimastering::Kpi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Kpi' do
    it 'should create an instance of Kpi' do
      expect(@instance).to be_instance_of(Aimastering::Kpi)
    end
  end
end

